name: assistad
favicon: null
layout_spectrum: 0.9776838440448046
typography_spectrum: 0.2988469582051039
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006396'
    - '#71c0e2'
    - '#000000'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
